/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTB1 (number 17), J8[2]/ADC0_SE5/CMP0_IN3/UART0_TX/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_TX_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_TX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB2 (number 18), J8[1]/ADC0_SE4/UART0_RX/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART0_RX_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART0_RX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTB3 (number 23), J7[10]/I2C0_SCL/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2C0PINS_ACCEL_SCL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C0PINS_ACCEL_SCL_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_I2C0PINS_ACCEL_SCL_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORTB4 (number 24), J7[9]/I2C0_SDA/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_I2C0PINS_ACCEL_SDA_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_I2C0PINS_ACCEL_SDA_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_I2C0PINS_ACCEL_SDA_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_I2C0Pins(void);

/*! @name PORTA10 (number 21), J8[5]/IRQ_8
  @{ */

/* Symbols to be used with GPIO driver */
#define MMA8451Q_INITPINS_ACCEL_IRQ_8_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define MMA8451Q_INITPINS_ACCEL_IRQ_8_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define MMA8451Q_INITPINS_ACCEL_IRQ_8_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MMA8451Q_INITPINS_ACCEL_IRQ_8_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define MMA8451Q_INITPINS_ACCEL_IRQ_8_PIN 10U                   /*!<@brief PORT pin number */
#define MMA8451Q_INITPINS_ACCEL_IRQ_8_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void MMA8451Q_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
